import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import FileUpload from "../components/FileUpload"
import { FaBars, FaGithub, FaLinkedinIn } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import { useState } from "react";
import { HiMenuAlt4, HiX } from "react-icons/hi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [showMenu, setShowMenu] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="page home">
        <div className="links-holder">
          <a href="https://github.com/bytegen-dev/cloud-uploads" className="link-btn" target="_blank" rel="noreferrer">
            <FaGithub />
          </a>
          <a href="https://x.com/bytegen-dev" className="link-btn" target="_blank" rel="noreferrer">
            <FaXTwitter />
          </a>
          <a href="https://linkedin.com/in/bytegen-dev" className="link-btn" target="_blank" rel="noreferrer">
            <FaLinkedinIn />
          </a>
        </div>
        <div className={`menu ${showMenu ? "show" : ""}`}>
          Menu
        </div>
        <div className="header">
          <div className="heading left">
            Cloudx
          </div>
          <div className="heading right">
            <div className="current-bucket">Spacelabz project</div>
            <div className="hamburger" onClick={()=>{
              setShowMenu(!showMenu)
            }}>
               {showMenu ? <HiX size={30} /> : <HiMenuAlt4 size={35} />}
            </div> 
          </div>
        </div>
      <div className="upload-holder">
        <h1>Upload Images</h1>
        <FileUpload />
      </div>
      </main>
    </>
  );
}
